// Resolution 16:9

#define PIXEL_BLOCK_SIZE 80  // HD
#define OBJECTW_W_TO_MENUW_W_RATIO (16 - 4)
// Main Window ---------------→
#define INIT_AX_MAIN_WINDOW 400
#define INIT_AY_MAIN_WINDOW 200
#define INIT_W_MAIN_WINDOW (16 * PIXEL_BLOCK_SIZE)
#define INIT_H_MAIN_WINDOW (9 * PIXEL_BLOCK_SIZE)

// Object Widget ----------→
#define INIT_AX_OBJECT_WIDGET \
  ((16 - OBJECTW_W_TO_MENUW_W_RATIO) * PIXEL_BLOCK_SIZE)
#define INIT_AY_OBJECT_WIDGET 0
#define INIT_W_OBJECT_WIDGET (OBJECTW_W_TO_MENUW_W_RATIO * PIXEL_BLOCK_SIZE)
#define INIT_H_OBJECT_WIDGET (9 * PIXEL_BLOCK_SIZE)

// Menu Widget ----------→
#define INIT_AX_MENU_WIDGET 0
#define INIT_AY_MENU_WIDGET 0
#define INIT_W_MENU_WIDGET \
  ((16 - OBJECTW_W_TO_MENUW_W_RATIO) * PIXEL_BLOCK_SIZE)
#define INIT_H_MENU_WIDGET (9 * PIXEL_BLOCK_SIZE)
